### PR TITLE
Implement a basic Metadata API

### LINKED ISSUE #4: Perform database hydration for metadata
Preprocess the dataset and hydrate the database.

- [x] Select X movies from different segments (e.g., decade) that are appropriate for questioning (e.g., based on popularity)
  - This can be used to adjust difficulty levels etc. in the future
  - The bonus question can display three movies from different segments
  - E.g., 2005-2020, 1990-2005, 1960-1990
- [x] Ensure that each of the selected movies is also available in OMDB

### LINKED ISSUE #6: Create API for Movie Metadata
### Related User Story & Issues
Story: https://github.com/kwizapp/kwiz/issues/5

### Description

Add an API endpoint that returns movie metadata for a specific Imdb ID, or, if none is provided, for a random movie.

### Tasks

- [x] Build a basic API that fetches movies from the database based on Imdb ID
- [x] Add integration tests for the database interactions 
- [x] Add validation of the Imdb ID based on common library code

### PR DESCRIPTION
**Pull request by rschlaefli**
### Description

This PR adds the following:

- An endpoint to fetch movie metadata based on an imdb id or randomly
- A Jupyter Notebook that processes our datasets and feeds the Database
  - Also checks for consistency with `poster-service` -> 149 are written to DB
- A production Dockerfile and garden configuration for the module
- E2E tests with `supertest` and `jest`

### Related Issues

Story: https://github.com/kwizapp/kwiz/issues/5
Issue: #6

### Checklist

- [x] Have you added tests where necessary? Do all the test pass? 
- [x] Have you added descriptive comments to your code?
- [x] Have you updated the documentation related to this

### CODE REVIEW

**Comment by rschlaefli** [comment]
@nikzaugg @alexscheitlin Ready for review. If we merge ASAP, we can start working with that stuff in Nest etc.

@nikzaugg I have introduced `supertest` in here, as it makes testing much easier than the very basic `test-listen`. Also, `request-promise` has been deprecated a long time ago. Just have a look in the code :)

**Comment by nikzaugg** [comment]
Good work! Thanks.

It took some time again to understand what to do with the database hydration etc. It was not clear to me how to actually run the  `Preprocessing.ipynb`. I then created an easier environment setup for conda with an `environment.yml`. 

Additionally, I found a way to produce a python file from the `Preprocessing.ipynb`, which made it more intuitive for me to run the hydration. (I've never really worked with jupyter notebooks)

It's all in the `README`. I've tried to make it clearer now. :-)

**Review by nikzaugg — CHANGES_REQUESTED** [review]
Alex and me noticed that there seems to be a problem with database connections that are not closed. I'm not sure if you already looked at this?
Currently on Heroku, it says **Utilization 20/20 connections**.

And I'm getting the following when i try to `npm run dev` locally: `UnhandledPromiseRejectionWarning: error: too many connections for role "powehcwhsbjgua"` .

You might need to close (`client.end()`) the connections in `dbService.fetchRandomMovieId` and `dbService.fetchRandomMovie` as well. I haven't tried.

Also, how do we get rid of the **20/20** on Heroku? :-P

**Comment by alexscheitlin** [comment]
> Alex and me noticed that there seems to be a problem with database connections that are not closed. I'm not sure if you already looked at this?
> Currently on Heroku, it says **Utilization 20/20 connections**.
> 
> And I'm getting the following when i try to `npm run dev` locally: `UnhandledPromiseRejectionWarning: error: too many connections for role "powehcwhsbjgua"` .
> 
> You might need to close (`client.end()`) the connections in `dbService.fetchRandomMovieId` and `dbService.fetchRandomMovie` as well. I haven't tried.
> 
> Also, how do we get rid of the **20/20** on Heroku? :-P

Using the heroku cli, we can get then same information from the web ui:
`heroku pg:info -a kwiz-metadata-service`

To close all open connections, we can use: 
`heroku pg:killall -a kwiz-metadata-service`

**Comment by alexscheitlin** [comment]
Nice work @rschlaefli!

We should add to the API Doc how to get a random movie (GET to the root '/'). How is the API Doc designed to work? Shouldn't we make one table with all requests?

**Comment by rschlaefli** [comment]
> Alex and me noticed that there seems to be a problem with database connections that are not closed. I'm not sure if you already looked at this?
> Currently on Heroku, it says **Utilization 20/20 connections**.
> 
> And I'm getting the following when i try to `npm run dev` locally: `UnhandledPromiseRejectionWarning: error: too many connections for role "powehcwhsbjgua"` .
> 
> You might need to close (`client.end()`) the connections in `dbService.fetchRandomMovieId` and `dbService.fetchRandomMovie` as well. I haven't tried.
> 
> Also, how do we get rid of the **20/20** on Heroku? :-P

Yes, this might have been old connections that were never closed and were (or still are) opened by my tests. But I am not sure and will have to find out how often Heroku cleans up stale connections

Edit: I think the reason was that the Preprocessing script did not properly close its connections. That is fixed now :)

**Comment by rschlaefli** [comment]
> Nice work @rschlaefli!
> 
> We should add to the API Doc how to get a random movie (GET to the root '/'). How is the API Doc designed to work? Shouldn't we make one table with all requests?

I would leave the API doc specifics and decisions for the separate issue that we opened (thinking about how we want to do API docs etc.). Otherwise we pull that work into this PR and it gets too big. I think it is ok in this PR as the id is marked as not required and it states that a random movie will be returned if no id is passed.

But @alexscheitlin it might be good to carry on with that discussion in the other issue (I assigned it to all of us yesterday, as it is relevant for Nest and both microservices).

**Review by alexscheitlin — APPROVED** [review]

**Comment by rschlaefli** [comment]
> Good work! Thanks.
> 
> It took some time again to understand what to do with the database hydration etc. It was not clear to me how to actually run the `Preprocessing.ipynb`. I then created an easier environment setup for conda with an `environment.yml`.
> 
> Additionally, I found a way to produce a python file from the `Preprocessing.ipynb`, which made it more intuitive for me to run the hydration. (I've never really worked with jupyter notebooks)
> 
> It's all in the `README`. I've tried to make it clearer now. :-)

Thanks, makes sense to have it in a Python script (as well). I normally develop in a notebook and eventually export it to pure Python. Might have been easier to understand if I did that in the PR ;)

@nikzaugg you should look at the notebook stuff, as it is really useful, and VSCode has a nice extension that can display the notebooks as well!

**Review by nikzaugg — APPROVED** [review]

**Pull request merged**
